#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$do\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${APP_DB_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${APP_DB_USER}', '${APP_DB_PASSWORD}');
  END IF;

  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${NANGO_DB_USER}') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${NANGO_DB_USER}', '${NANGO_DB_PASSWORD}');
  END IF;
END
\$do\$;

DO
\$do\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '${APP_DB_NAME}') THEN
    EXECUTE format('CREATE DATABASE %I OWNER %I', '${APP_DB_NAME}', '${APP_DB_USER}');
  END IF;

  IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '${NANGO_DB_NAME}') THEN
    EXECUTE format('CREATE DATABASE %I OWNER %I', '${NANGO_DB_NAME}', '${NANGO_DB_USER}');
  END IF;
END
\$do\$;

GRANT ALL PRIVILEGES ON DATABASE "${APP_DB_NAME}" TO "${APP_DB_USER}";
GRANT ALL PRIVILEGES ON DATABASE "${NANGO_DB_NAME}" TO "${NANGO_DB_USER}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB_NAME" <<-EOSQL
ALTER SCHEMA public OWNER TO "${APP_DB_USER}";
GRANT ALL ON SCHEMA public TO "${APP_DB_USER}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$NANGO_DB_NAME" <<-EOSQL
ALTER SCHEMA public OWNER TO "${NANGO_DB_USER}";
GRANT ALL ON SCHEMA public TO "${NANGO_DB_USER}";
EOSQL
